# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'donationApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for donationApp

  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'R.swift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'SwiftyUtils'
  pod 'ReachabilitySwift', '~> 3'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'
end
